### ISSUE TITLE
Написать readme файл

### ISSUE THREAD

**Issue by Alt90** [krasnov14107/cat_in_boots#1]
Расписать что за проект. Как им пользоваться. И что он делает. Если нужно ставить пакеты то создать  requirements.txt.

**Comment by krasnov14107** [comment]
https://github.com/krasnov14107/cat_in_boots/blob/master/geoConstructor/readme.txt

**Comment by krasnov14107** [comment]
Или мне нельзя закрывать задания так?

**Comment by Alt90** [comment]
Дажае нужно.
